### ISSUE TITLE
Metadata and Conversion Panels not displayed properly on MacOS

### ISSUE THREAD

**Issue by sohantamang** [bgoldbeck/lscan#40]
### Description
Metadata panel and Conversion panel in LSCan are disoriented and not visible on MacOS only. The local environment has all the required packages and using Python 3.7. The panels appear when the height of LScan is increased.

### Reproduction Steps
Run updated LScan on MacOS.
Video link: https://drive.google.com/open?id=1uMUKGWrAYcR2HjHs_BegoGF6Msw3CTUG

### Acceptance Criteria
Metadata panel and conversion panel appers
![lscanpanel](https://user-images.githubusercontent.com/18367858/52538683-62bde800-2d2a-11e9-984f-b9f4371b4ff8.png)

**Comment by greenunknown** [comment]
I'm having issues viewing the video. Do you have screenshots?

**Comment by sohantamang** [comment]
The video is in Google Drive `capstone/livingdocument/v&v/videos`.  I will attach some screenshots tomorrow.

**Comment by sohantamang** [comment]
Reappeared after yesterday's merges.
