### ISSUE TITLE
Pause/Continue Label Appears and Toggles Normally after Clicking Once

### ISSUE THREAD

**Issue by sohantamang** [bgoldbeck/lscan#42]
### Description
Upon starting LScan `Pause/Continue` button appears. During the conversion process, the button is clickable but the label still appears `Pause/Continue`. However, Clicking once it toggles normally.

### Reproduction Steps
1. Open LScan and view the label for `Pause` button in conversion panel

### Acceptance Criteria
1. Label `Pause` appears by default
2. When the `Convert` button is pressed, the label should be `Pause`
![during-conversion](https://user-images.githubusercontent.com/18367858/52538925-48393e00-2d2d-11e9-84f5-893e2ca0c343.png)

**Comment by annelidae** [comment]
This has been fixed on master
