### ISSUE TITLE
File overwrite for output doesn't popup the confirm overwrite window and locks up the program (ui becomes unresponsive).

### ISSUE THREAD

**Issue by greenunknown** [bgoldbeck/lscan#49]
![image](https://user-images.githubusercontent.com/12701414/52906310-f6e1f080-31fd-11e9-9694-bd3cbb69518c.png)

Maybe unbind then rebind to allow the overwrite with new events. Opengl and wxpython interaction issue. Disable opengl at certain points.

**Comment by Hentaikamenride** [comment]
Just a note for who got that issue.
This is related to display problem. Click Alt button on keyboard (Enter or Escape alternatively)
The reason is caused by OpenGL overlapping wxMessagebox.
