### ISSUE TITLE
Replace File Dialog does not appear, LScan freezes: Windows OS

### ISSUE THREAD

**Issue by sohantamang** [bgoldbeck/lscan#76]
Windows OS:
User cannot perform multiple conversion in one session if they try to replace the old file. 

## Reproduction Steps

1.  Convert a STL file to `untitled.dat`
2. Once the conversion is done, click output file and put `untitled.dat` for output file name
3. Program freezes until `Alt` key is pressed.

**Comment by greenunknown** [comment]
Fix/replace file dialog does not appear lscan freezes win #77
